#include "prx/libSceAgcDriver/Execution/include/Driver/Driver.hpp"

namespace AgcDriver::DriverDetail {

void Driver::reportDrawCache(DrawEntryCounters& counters) {
    const auto count = [](std::uint64_t value) { return static_cast<unsigned long long>(value); };
    const auto validated = counters.lookups - counters.absent;
    const auto miss = [&](DrawMiss reason) { return count(counters.misses[static_cast<std::size_t>(reason)]); };
    std::string ranks;
    for (std::size_t rank = 0; rank < dispatchVariants(); ++rank) {
        char text[32];
        std::snprintf(text, sizeof(text), "%s%llu", rank == 0 ? "" : " / ", count(counters.variantHitsByRank[rank]));
        ranks += text;
    }
    std::fprintf(stderr, "[draw-cache] %llu lookups (10 s): %llu no entry, %llu validated in %.1f us each (key, lookup and every stage): %llu hits (every stage equal; stage hits by variant rank 1..k %s), misses by reason: front stage differing %llu, fragment differing %llu, other stage differing %llu, layout (push offset) %llu, gate %llu, stage count %llu; %llu stage validations (%llu equal, %.2f variants compared each); %llu inserts (%llu variants inserted, %llu evicted beyond k, %llu already present, %llu unstable), %zu entries (%llu variants, ~%.1f MiB), %llu evictions in total, %llu LRU moves; verify: %llu hits captured again, %llu stages differed\n", count(counters.lookups), count(counters.absent), count(validated), validated != 0 ? counters.validateUs / static_cast<double>(validated) : 0.0, count(counters.hits), ranks.c_str(), miss(DrawMiss::FrontDiffering), miss(DrawMiss::FragmentDiffering), miss(DrawMiss::OtherDiffering), miss(DrawMiss::Layout), miss(DrawMiss::Gate), miss(DrawMiss::Stages), count(counters.stageValidations), count(counters.stageEqual), counters.stageValidations != 0 ? static_cast<double>(counters.variantsCompared) / static_cast<double>(counters.stageValidations) : 0.0, count(counters.inserts), count(counters.variantsInserted), count(counters.variantsEvicted), count(counters.present), count(counters.unstable), drawCache.size(), count(drawCacheVariants), static_cast<double>(drawCacheVariantBytes) / (1024.0 * 1024.0), count(drawCacheEvictions), count(counters.touches), count(counters.verifyHits), count(counters.verifyMismatches));
    std::fprintf(stderr, "[draw-cache] register key (10 s): %llu lookups, %llu hits, key build %.1f us each; decode skipped %llu, partial (state/pixel/programs from the entry) %llu; facade log != table %llu; verify: %llu decodes compared, %llu differed\n", count(counters.registerKeyLookups), count(counters.registerKeyHits), counters.registerKeyLookups != 0 ? counters.keyUs / static_cast<double>(counters.registerKeyLookups) : 0.0, count(counters.decodeSkipped), count(counters.decodePartial), count(counters.facadeMismatches), count(counters.verifyDecodes), count(counters.verifyDecodeMismatches));
    std::fprintf(stderr, "[draw-cache] data hits (10 s): %llu (%llu stages, %llu words refreshed), verified %llu; inserts with data positions %llu (%.1f positions each); partial hits %llu (%llu stages kept); T# bits ignored: %llu words accepted, %llu inserts with ignored positions (%.1f each); V# bases: %llu stages refreshed, %llu inserts with base slots (%.1f each); elements skipped: written %llu, not among the words %llu, not read by the walk %llu, ambiguous %llu, at data positions %llu\n", count(counters.dataHits), count(counters.dataStages), count(counters.dataWordsRefreshed), count(counters.dataVerified), count(counters.dataInserts), counters.dataInserts != 0 ? static_cast<double>(counters.dataPositionsInserted) / static_cast<double>(counters.dataInserts) : 0.0, count(counters.partialHits), count(counters.partialStagesKept), count(ignoredBitWords.exchange(0, std::memory_order_relaxed)), count(counters.ignoredInserts), counters.ignoredInserts != 0 ? static_cast<double>(counters.ignoredPositionsInserted) / static_cast<double>(counters.ignoredInserts) : 0.0, count(counters.baseStages), count(counters.baseInserts), counters.baseInserts != 0 ? static_cast<double>(counters.baseSlotsInserted) / static_cast<double>(counters.baseInserts) : 0.0, count(counters.baseWritten), count(counters.baseUnlocated), count(counters.baseUnread), count(counters.baseAmbiguous), count(counters.baseData));
    if (drawEvictedKeyBound() != 0) {
        const auto entries = static_cast<unsigned long long>(drawCacheEntries());
        std::uint64_t evicted = 0;
        for (const auto value : counters.absentEvicted) evicted += value;
        std::fprintf(stderr, "[draw-cache] absent keys (10 s): %llu evicted before (would have hit with <= %llu entries %llu, <= %llu %llu, <= %llu %llu, <= %llu %llu, <= %llu %llu, more %llu), %llu never seen (new, or evicted beyond the last %zu evictions; %llu with a known base key); %zu evicted keys remembered\n", count(evicted), entries * 2, count(counters.absentEvicted[0]), entries * 4, count(counters.absentEvicted[1]), entries * 8, count(counters.absentEvicted[2]), entries * 16, count(counters.absentEvicted[3]), entries * 32, count(counters.absentEvicted[4]), count(counters.absentEvicted[5]), count(counters.absentNew), drawEvictedKeyBound(), count(counters.absentNewBaseKnown), drawEvictedKeys.size());
    }
    const auto perValidated = [&](double us) { return validated != 0 ? us / static_cast<double>(validated) : 0.0; };
    std::fprintf(stderr, "[draw-cache] validate split (10 s), us per validated lookup: key %.2f, stage compares %.2f (%llu validateVariant calls), patched results %.2f (%llu made, %llu reused), rest %.2f\n", perValidated(counters.keyUs), perValidated(counters.compareUs), count(counters.compareCalls), perValidated(counters.patchUs), count(counters.patchedMade), count(counters.patchedReused), perValidated(counters.validateUs - counters.keyUs - counters.compareUs - counters.patchUs));
    const auto verdict = [&](RelocationVerdict value) { return count(counters.relocationVerdicts[static_cast<std::size_t>(value)]); };
    std::fprintf(stderr, "[draw-cache] relocation (10 s): new keys with a candidate under the base key %llu (none %llu; candidates examined %llu, pointer pairs disagreeing %llu, rejected by the shifted words %llu, none chosen %llu, learned from %llu); relocated hits %llu (%llu stages shifted, %llu compared in place), partial %llu; stages without a rule %llu, shifted variant differing %llu, unordered %llu; learned %llu of %llu (shape %llu, data positions %llu, deltas %llu, nothing moved %llu, other words %llu, no pointer %llu, compiled %llu, descriptors %llu); %llu rekeys, %zu base keys indexed\n", count(counters.relocationCandidates), count(counters.relocationNoCandidate), count(counters.relocationTried), count(counters.relocationDeltas), count(counters.relocationQuickRejected), count(counters.relocationUnchosen), count(counters.relocationLearnedFrom), count(counters.relocatedHits), count(counters.relocatedStages), count(counters.relocatedInPlace), count(counters.relocatedPartial), count(counters.relocationNoRule), count(counters.relocationDiffering), count(counters.relocationUnordered), count(counters.relocationLearned), count(counters.relocationLearnAttempts), verdict(RelocationVerdict::Shape), verdict(RelocationVerdict::DataPositions), verdict(RelocationVerdict::Deltas), verdict(RelocationVerdict::NothingMoved), verdict(RelocationVerdict::OtherWords), verdict(RelocationVerdict::NoPointer), verdict(RelocationVerdict::Compiled), verdict(RelocationVerdict::Descriptors), count(counters.rekeys), drawBaseIndex.size());
    const auto relocationUs = counters.relocationFindUs + counters.relocationChooseUs + counters.relocationDecodeUs + counters.relocationRekeyUs;
    if (relocationUs != 0) {
        const auto ms = [](double us) { return us / 1000.0; };
        std::fprintf(stderr, "[draw-cache] relocation cost (10 s): candidate search %.1f ms, choice %.1f ms, decode copies %.1f ms, rekeys %.1f ms = %.2f us per lookup\n", ms(counters.relocationFindUs), ms(counters.relocationChooseUs), ms(counters.relocationDecodeUs), ms(counters.relocationRekeyUs), counters.lookups != 0 ? relocationUs / static_cast<double>(counters.lookups) : 0.0);
    }
    counters = DrawEntryCounters{};
}

}
